[package]
name = "server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "tscanner-server"
path = "src/main.rs"

[dependencies]
core = { path = "../core" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
flate2 = "1.0"
base64 = "0.21"
pathdiff = { workspace = true }
walkdir = { workspace = true }
glob = "0.3"
lsp-types = "0.95"
lsp-server = "0.7"
