[package]
name = "tscanner_output"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tscanner_config = { path = "../tscanner_config" }
tscanner_types = { path = "../tscanner_types" }
serde = { workspace = true }
serde_json = { workspace = true }
pathdiff = { workspace = true }
