[package]
name = "tscanner_constants"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lazy_static = "1.4"
serde = { workspace = true }
serde_json = { workspace = true }
tscanner_types = { path = "../tscanner_types" }
