[package]
name = "tscanner_config"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tscanner_types = { path = "../tscanner_types" }
tscanner_constants = { path = "../tscanner_constants" }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
globset = { workspace = true }
json_comments = { workspace = true }
regex = { workspace = true }
lazy_static = "1.4"
which = { workspace = true }
