[package]
name = "core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "generate_schema"
path = "src/bin/generate_schema.rs"

[dependencies]
swc_ecma_parser = { workspace = true }
swc_ecma_ast = { workspace = true }
swc_ecma_visit = { workspace = true }
swc_common = { workspace = true }
rayon = { workspace = true }
dashmap = { workspace = true }
walkdir = { workspace = true }
ignore = { workspace = true }
globset = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
json_comments = { workspace = true }
schemars = { workspace = true }
notify = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
regex = { workspace = true }
pathdiff = { workspace = true }
inventory = "0.3"
time = { version = "0.3", features = ["formatting", "macros"] }
