[package]
name = "tscanner_service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tscanner_types = { path = "../tscanner_types" }
tscanner_config = { path = "../tscanner_config" }
tscanner_rules = { path = "../tscanner_rules" }
tscanner_cache = { path = "../tscanner_cache" }
tscanner_scanner = { path = "../tscanner_scanner" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
lazy_static = "1.4"
parking_lot = "0.12"
