[package]
name = "tscanner_cache"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tscanner_types = { path = "../tscanner_types" }
dashmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dirs = "5.0"
